name: production-healthcheck

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  health:
    uses: gorfednet/.github/.github/workflows/production-healthcheck.yml@main
    with:
      site-url: https://subrythm.com
      run-playwright: false
